In [35]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [36]:
tf.__version__

'2.2.0'

In [37]:
from google.colab import drive

In [38]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [39]:
dataset = pd.read_excel('/content/drive/My Drive/ANN_Regression/Folds5x2_pp.xlsx')

In [40]:
dataset.shape

(9568, 5)

In [41]:
dataset.head(10)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
5  26.27  59.44  1012.23  58.77  443.67
6  15.89  43.96  1014.02  75.24  467.35
7   9.48  44.71  1019.12  66.43  478.42
8  14.64  45.00  1021.78  41.25  475.98
9  11.74  43.56  1015.14  70.72  477.50

In [42]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [43]:
print(X), print(Y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


(None, None)

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split (X, Y, test_size = 0.2, random_state = 0)

In [45]:
ann = tf.keras.models.Sequential()

In [46]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [47]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [48]:
ann.add(tf.keras.layers.Dense(units = 1))

In [49]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [50]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 114944.5234
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 654.8953
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 595.4974
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 571.3771
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 543.8945
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 512.9078
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 479.5665
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 443.5088
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 407.2652
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 368.7604
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 331.9995
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

In [57]:
Y_pred = ann.predict(X_test)

In [59]:
np.set_printoptions(precision = 2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)), 1))

[[430.04 431.23]
 [460.82 460.01]
 [464.24 461.14]
 ...
 [471.48 473.26]
 [438.48 438.  ]
 [457.55 463.28]]
